### ISSUE TITLE
ImportError: No module named pylti.flask

### ISSUE THREAD

**Issue by SoxFace** [kajigga/instcon2017-ltisession#1]
Hi Kevin, 

I think this is more a pythonanywhere.com question.

I'm currently on Step 3 (thanks for the video) and I'm getting ImportError: 

```
Error running WSGI application
ImportError: No module named pylti.flask
File "/var/www/soxface_pythonanywhere_com_wsgi.py", line 16, in <module>
  from instcon_flaskapp import app as application
File "/home/soxface/instcon2017/instcon_flaskapp.py", line 7, in <module>
  from pylti.flask import lti
***************************************************
If you're seeing an import error and don't know why,
we have a dedicated help page to help you debug: 
https://help.pythonanywhere.com/pages/DebuggingImportError/
***************************************************
```
When I go to the link and run the command from the link, I get:

```
22:28 ~/instcon2017 (master)$ python -i /var/www/soxface_pythonanywhere_com_wsgi.py
Traceback (most recent call last):
  File "/var/www/soxface_pythonanywhere_com_wsgi.py", line 16, in <module>
    from instcon_flaskapp import app as application
  File "/home/soxface/instcon2017/instcon_flaskapp.py", line 7, in <module>
    from pylti.flask import lti
ImportError: No module named pylti.flask
```

any thoughts?

**Comment by kajigga** [comment]
Your virtual environment is missing the pylti module. 
What you need to do is install it by running 

`pip install pylti`

You have to do this while you're in your web applications virtual environment. 

What you need to do is, after entering the python anywhere console, is type in the following.

```bash
workon <yourusername>.pythonanywhere.com
pip install pylti
```

**Comment by kajigga** [comment]
Make sure you replace `<yourusername>` with your own username

**Comment by stephenwoosley** [comment]
Hi @kajigga, thanks again for creating such thorough walk-thru videos. I've had the same problem as @SoxFace, and have gone through the installation steps you listed above. Any ideas why the same (verbatim) error would be occurring?
